# Generated by Django 4.0.5 on 2022-12-05 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='date_joined',
            field=models.DateField(default=datetime.date(2022, 12, 5)),
        ),
    ]
